#!/usr/bin/env python3
"""Generate font_atlas.h from a monospace TTF for CosmoRT VT.

Usage: python3 tools/mkfont.py fonts/Hack-Regular.ttf src/kernel/font_atlas.h

Dependencies: pip install Pillow fonttools
"""

import sys
from fontTools.ttLib import TTFont
from PIL import Image, ImageDraw, ImageFont


def get_codepoints(ttf_path):
    """Extract actual codepoints from the font's cmap table."""
    tt = TTFont(ttf_path)
    cmap = tt.getBestCmap()
    tt.close()
    # Filter out control chars below SPACE (keep U+0020+)
    return sorted(cp for cp in cmap if cp >= 0x20)


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <font.ttf> <output.h>", file=sys.stderr)
        sys.exit(1)

    ttf_path, out_path = sys.argv[1], sys.argv[2]
    SIZE = 16

    font = ImageFont.truetype(ttf_path, SIZE)

    # Cell size from metrics (monospace: all glyphs same advance)
    cell_w = int(font.getlength('M'))
    asc, desc = font.getmetrics()
    cell_h = asc + desc
    print(f"Cell: {cell_w}x{cell_h}, ascent={asc}, descent={desc}")

    # Actual codepoints from font cmap
    codepoints = get_codepoints(ttf_path)
    print(f"Codepoints: {len(codepoints)}")

    # Render all glyphs
    glyphs = []
    glyph_map = []
    for idx, cp in enumerate(codepoints):
        img = Image.new('L', (cell_w, cell_h), 0)
        draw = ImageDraw.Draw(img)
        draw.text((0, 0), chr(cp), fill=255, font=font)
        glyphs.append(bytes(img.getdata()))
        glyph_map.append((cp, idx))

    num_glyphs = len(glyphs)
    total_bytes = num_glyphs * cell_w * cell_h
    print(f"Glyphs: {num_glyphs}, data: {total_bytes} bytes ({total_bytes / 1024:.1f} KB)")

    # Write header
    with open(out_path, 'w') as f:
        f.write("/* Generated by tools/mkfont.py -- do not edit */\n")
        f.write("#ifndef FONT_ATLAS_H\n#define FONT_ATLAS_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define FONT_BASE_W {cell_w}\n")
        f.write(f"#define FONT_BASE_H {cell_h}\n")
        f.write(f"#define FONT_NUM_GLYPHS {num_glyphs}\n\n")

        # Glyph map (sorted by codepoint for binary search)
        f.write("typedef struct {\n")
        f.write("    uint32_t codepoint;\n")
        f.write("    uint16_t index;\n")
        f.write("} font_glyph_map_t;\n\n")
        f.write("static const font_glyph_map_t font_map[] = {\n")
        for cp, i in glyph_map:
            f.write(f"    {{ 0x{cp:04X}, {i} }},\n")
        f.write("};\n")
        f.write("#define FONT_MAP_SIZE (sizeof(font_map) / sizeof(font_map[0]))\n\n")

        # Glyph data: row-major, 32 values per line
        f.write("static const uint8_t font_data[] = {\n")
        COLS = 32
        for gi, data in enumerate(glyphs):
            f.write(f"    /* glyph {gi}: U+{glyph_map[gi][0]:04X} */\n")
            for off in range(0, len(data), COLS):
                chunk = data[off:off + COLS]
                f.write("    ")
                f.write(",".join(str(b) for b in chunk))
                f.write(",\n")
        f.write("};\n\n")
        f.write("#endif /* FONT_ATLAS_H */\n")

    print(f"Written: {out_path}")


if __name__ == '__main__':
    main()
